import styled from "@emotion/styled";
import { Stack } from "@mui/material";
import Head from "next/head";
import { useState } from "react";

import { Timer, Todos } from "./components";
import { TimerState } from "./components/timer-reducer";

export default function Home() {
  const [selectedTodo, setSelectedTodo] = useState("");
  const [timerState, setTimerState] = useState<TimerState>(TimerState.Stopped);

  function onSelectedTodoChanged(todo: string) {
    setSelectedTodo(todo);
  }

  function onTodoStarted(timerState: TimerState) {
    setTimerState(timerState);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack spacing={2}>
        <TimerWrapper>
          <Timer {...{ todo: selectedTodo, onTodoStarted }} />
        </TimerWrapper>
        <TodosWrapper>
          <Todos
            {...{ todo: selectedTodo, onSelectedTodoChanged, timerState }}
          />
        </TodosWrapper>
      </Stack>
    </>
  );
}

const TimerWrapper = styled.div`
  background-color: orange;
  border-radius: 5px;
  padding: 3vh;
`;

const TodosWrapper = styled.div`
  padding: 3vh;
  border-radius: 5px;
`;
